### ISSUE TITLE
Thank you for this! Does this work on GitHub pages please? 

### ISSUE THREAD

**Issue by jaanaltosaar** [Xairoo/nextjs-i18n-static-page-starter#7]
(We really need this feature for www.Payless.health)

**Comment by xairoo** [comment]
I haven't used GitHub Pages before, only Cloudflare Pages (it's also free, blazing fast and it's a good idea to use Cloudflare instead of GitHub Pages), but a quick Google search showed me that it should work.
Anyway, I would go with Cloudflare Pages :)
Don't see a benefit to use GitHub Pages.

https://dev.to/github/how-to-host-a-static-nextjs-site-on-github-pages-4pe0

**Comment by xairoo** [comment]
Btw. I just noticed that this repo is an old starter.

You should use https://github.com/xairoo/next-i18next-static-site

> 🔥🔥🔥  
> I released a better solution: [next-i18next-static-site](https://www.npmjs.com/package/next-i18next-static-site)  
> This package brings you `react-i18next` and `i18next` to your static sites build with the `next export` future from Next.js.  
>  
> - 🗲 Translation is already rendered (SSG), client will receive the final translated site.  
> - 🔥 Hot reload works also when you update your locale (translation) files.  
> - 🚀 Automatic browser language detection can be realized.  
> - 🍪 Cookie stores the client language.  
>  
> It's highly recommend to use [next-i18next-static-site](https://www.npmjs.com/package/next-i18next-static-site) instead of this starter if you want to use all functions from `react-i18next`.
